name: cinepulse
description: 'Explore the cinematic universe with "CinePeek"! This app lets you discover upcoming blockbusters, trending films, and personalized recommendations, all while enjoying a seamless, visually stunning experience with offline access.'
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  skeletonizer: ^2.0.0
  flutter_riverpod: ^3.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  http: ^1.0.0
  cached_network_image: ^3.0.0
  shared_preferences: ^2.0.0
  provider: ^6.0.0
  url_launcher: ^6.0.0
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.4
  build_runner: ^2.4.8
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
